spring.application.name=student-leave-request-portal

spring.datasource.url=jdbc:mysql://localhost:3306/student_leave_request_portal
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect